-- =============================================================================
-- 32_dim_familia.sql
-- Dimensión de familia profesional.
-- =============================================================================

DROP TABLE IF EXISTS gold.dim_familia CASCADE;

CREATE TABLE gold.dim_familia (
    sk_familia integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_familia text NOT NULL UNIQUE
);

INSERT INTO gold.dim_familia (sk_familia, nom_familia) VALUES (-1, 'No informado');

INSERT INTO gold.dim_familia (nom_familia)
SELECT DISTINCT nom_familia
FROM   silver.poblacion
WHERE  nom_familia IS NOT NULL
  AND  trim(nom_familia) <> ''
  AND  nom_familia <> 'No informado'
ORDER  BY nom_familia;

SELECT count(*) AS familias FROM gold.dim_familia;
