-- =============================================================================
-- 33_dim_programa.sql
-- Dimensión de programa (ciclo formativo). Incluye el grado como atributo,
-- no como dimensión aparte: un ciclo pertenece siempre a un único grado.
-- =============================================================================

DROP TABLE IF EXISTS gold.dim_programa CASCADE;

CREATE TABLE gold.dim_programa (
    sk_programa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_ciclo   text NOT NULL,
    nom_grado   text NOT NULL,
    sk_familia  integer NOT NULL REFERENCES gold.dim_familia (sk_familia),
    UNIQUE (nom_ciclo, nom_grado, sk_familia)
);

INSERT INTO gold.dim_programa (sk_programa, nom_ciclo, nom_grado, sk_familia)
VALUES (-1, 'No informado', 'No informado', -1);

INSERT INTO gold.dim_programa (nom_ciclo, nom_grado, sk_familia)
SELECT DISTINCT
       coalesce(nullif(trim(p.nom_ciclo), ''), 'No informado'),
       p.nom_grado,
       coalesce(f.sk_familia, -1)
FROM   silver.poblacion p
LEFT   JOIN gold.dim_familia f ON f.nom_familia = p.nom_familia
WHERE  NOT (coalesce(nullif(trim(p.nom_ciclo), ''), 'No informado') = 'No informado'
            AND p.nom_grado = 'No informado'
            AND coalesce(f.sk_familia, -1) = -1);

CREATE INDEX idx_dim_programa_familia ON gold.dim_programa (sk_familia);

SELECT count(*) AS programas FROM gold.dim_programa;
