-- =============================================================================
-- 34_dim_atributos.sql
-- Dimensiones pequeñas: modalidad, sexo, tramo de edad, titularidad.
-- Todas con miembro 'No informado' en sk = -1.
-- =============================================================================

-- --------------------------------------------------- modalidad
DROP TABLE IF EXISTS gold.dim_modalidad CASCADE;

CREATE TABLE gold.dim_modalidad (
    sk_modalidad  integer PRIMARY KEY,
    nom_modalidad text NOT NULL UNIQUE
);

INSERT INTO gold.dim_modalidad (sk_modalidad, nom_modalidad) VALUES
    (-1, 'No informado'),
    (1,  'Presencial'),
    (2,  'Distancia'),
    (3,  'Dual');

-- --------------------------------------------------- sexo
DROP TABLE IF EXISTS gold.dim_sexo CASCADE;

CREATE TABLE gold.dim_sexo (
    sk_sexo  integer PRIMARY KEY,
    nom_sexo text NOT NULL UNIQUE
);

INSERT INTO gold.dim_sexo (sk_sexo, nom_sexo) VALUES
    (-1, 'No informado'),
    (1,  'Hombres'),
    (2,  'Mujeres'),
    (3,  'Ambos sexos');

-- --------------------------------------------------- titularidad
DROP TABLE IF EXISTS gold.dim_titularidad CASCADE;

CREATE TABLE gold.dim_titularidad (
    sk_titularidad  integer PRIMARY KEY,
    nom_titularidad text NOT NULL UNIQUE
);

INSERT INTO gold.dim_titularidad (sk_titularidad, nom_titularidad) VALUES
    (-1, 'No informado'),
    (1,  'Pública'),
    (2,  'Privada'),
    (3,  'Privada concertada');

-- --------------------------------------------------- tramo de edad
DROP TABLE IF EXISTS gold.dim_edad CASCADE;

CREATE TABLE gold.dim_edad (
    sk_edad        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_tramo_edad text NOT NULL UNIQUE,
    orden          integer
);

INSERT INTO gold.dim_edad (sk_edad, nom_tramo_edad, orden)
VALUES (-1, 'No informado', 999);

INSERT INTO gold.dim_edad (nom_tramo_edad, orden)
SELECT DISTINCT
       nom_tramo_edad,
       -- Ordena por el primer número que aparece en el literal del tramo
       coalesce((regexp_match(nom_tramo_edad, '(\d+)'))[1]::integer, 998)
FROM   silver.poblacion
WHERE  nom_tramo_edad <> 'No informado';

SELECT 'dim_modalidad'   AS dimension, count(*) FROM gold.dim_modalidad
UNION ALL SELECT 'dim_sexo',        count(*) FROM gold.dim_sexo
UNION ALL SELECT 'dim_titularidad', count(*) FROM gold.dim_titularidad
UNION ALL SELECT 'dim_edad',        count(*) FROM gold.dim_edad;
